[.NET] 01 - Back-End Criação do Usuário
natycanellas/EverestApi pull request #1
Opened 2022-12-06 20:07 UTC by natycanellas

[Link do card no Jira - EV976](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-976)

- [x] CRUD realizado com sucesso
- [x] Projeto separado da Main
- [x] Verificando os campos de cpf e e-mail
- [x] Retornos corretos dos endpoints

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Controllers/WeatherForecastController.cs
> +}
Remover este arquivo, pois não faz parte do desafio.

```suggestion
```

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/EverestAPI.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
```suggestion
```

Remover essas duas linhas e fazer os imports através dos usings explicitamente em cada classe.

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Models/CustomerModel.cs
> +        {
```suggestion
        public CustomerModel(
            string fullName, 
            string email, 
            string emailConfirmation, 
            string cpf, 
            string cellphone, 
            DateTime dateOfBirth, 
            bool emailSms, 
            bool whatsapp, 
            string country, 
            string city,
            string postalCode, 
            string address, 
            long id
        )
        {
```

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Program.cs
> +        app.Run();
Corrigir indentação. Usar o comando CTRL + K + D que faz isso automático.

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/WeatherForecast.cs
> +}
Remover do projeto, pois não faz parte do desafio.

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Services/ICustomerService.cs
> +        void Create(CustomerModel model);
```suggestion
        Long Create(CustomerModel model);
```
Deveria retornar o Id do Customer que acabou de ser criado. PS: Long foi só uma das hipóteses. Poderia ser int, Guid e etc.

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Services/ICustomerService.cs
> +        CustomerModel? GetById(long id);
```suggestion
        CustomerModel GetById(long id);
```

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Models/CustomerModel.cs
> +            long id
```suggestion
```
Remover o Id do construtor. Pois você possui uma regra de negócio que cria Ids de forma incremental na CustomerService. Dessa forma não faz sentido informar na requisição.

2022-12-07 14:13 UTC, DevClaudinei commented on EverestAPI/Services/CustomerService.cs
> +            if (response == null) throw new ArgumentException($"Customer with id: {id} was not found");
```suggestion
            if (response == null) throw new ArgumentNullException($"Customer for id: {id} not found");
```
A exceção lançada não está evitando que estoure o erro.

2022-12-07 14:13 UTC, santosclaudinei-warren commented on EverestAPI/Controllers/CustomerController.cs
> +        public IActionResult Update(CustomerModel customerModel)
```suggestion
        public IActionResult Update(CustomerModel customerModel, long id)
```
Você poderia capturar o id que vem da rota e utilizar ele para realizar a pesquisa do Customer a ser atualizado. Acredito que seja melhor que passar o id na rota e passar o id no body (corpo da requisição).

2022-12-12 18:57 UTC, gregoryzimmerwarren requested changes
Deixei alguns comentários e sugestões. Qualquer dúvida estou a disposição.

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/EverestAPI.csproj
> +    <PackageReference Include="FluentValidation" Version="11.4.0" />
```suggestion
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/EverestAPI.csproj
> +    <PackageReference Include="FluentValidation" Version="11.4.0" />
Esse package não é necessário.

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Models/StringExtensions.cs
> +            return cpf.Trim().Replace(".", "").Replace("-", "").Replace(" ", "");
```suggestion
            return cpf.Trim().Replace(".", "").Replace("-", "").Replace(" ", "").Replace(",","");
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Models/StringExtensions.cs
> +            return cpf.Trim().Replace(".", "").Replace("-", "").Replace(" ", "");
Eu colocaria apenas por garantia.

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Services/CustomerService.cs
> +        public void Update(CustomerModel updateModel, long id)
```suggestion
        }
        
        public void Update(CustomerModel updateModel, long id)
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Services/CustomerService.cs
> +        public CustomerModel GetById(long id)
```suggestion
        }
        
        public CustomerModel GetById(long id) 
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Services/CustomerService.cs
> +            if (response == null) throw new ArgumentNullException($"Customer for id: {id} was not found");
```suggestion
            if (response == null)
               throw new ArgumentNullException($"Customer for id: {id} was not found");
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Services/CustomerService.cs
> +            if (response == null) throw new ArgumentNullException($"Customer for id: {id} was not found");
Só confirma a indentação.

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Services/CustomerService.cs
> +        public void Delete(long Id)
```suggestion
        }
        
        public void Delete(long Id)
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Services/CustomerService.cs
> +        public IEnumerable<CustomerModel> GetAll()
```suggestion
        }
        
        public IEnumerable<CustomerModel> GetAll() 
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Validators/CustomerRulesValidator.cs
> +                .EmailAddress().WithMessage("Invalid Email format");
```suggestion
            RuleFor(customer => customer.Email)
                .NotEmpty()
                .EmailAddress()                
                .WithMessage("Invalid Email format");
```

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Validators/CustomerRulesValidator.cs
> +                .EmailAddress().WithMessage("Invalid Email format");
O NotEmpty já possui uma mensagem padrão, não precisa colocar o WithMessage dai.

Recomendo também refazer a mensagem de email e cpf inválidos, porque elas não estão deixando claro ao usuário como seria um formato válido para quando eles tentarem novamente. Podes pensar também em inserir em PostalCode e Cellphone para saberem qual seria o formato válido para eles também.

2022-12-12 18:57 UTC, gregoryzimmerwarren commented on EverestAPI/Validators/CustomerRulesValidator.cs
> +                .Must(OverAgeCustomer).WithMessage("Customer must be at least 18 years old");
```suggestion
                .NotEmpty()
                .Must(OverAgeCustomer)
                .WithMessage("Customer must be at least 18 years old");
```

2022-12-14 19:16 UTC, gregoryzimmerwarren approved these changes

2022-12-15 12:13 UTC, LuanFortunatoW approved these changes

2022-12-15 12:13 UTC, LuanFortunatoW commented on EverestAPI/Controllers/CustomerController.cs
> +        public IActionResult Update(CustomerModel customerModel, long id)
```suggestion
        [HttpPut("{id}")]
        public IActionResult Update([FromBody] CustomerModel customerModel, long id)
```

2022-12-15 16:48 UTC, santosclaudinei-warren approved these changes

2022-12-16 17:41 UTC, merged